spring:
  #  autoconfigure:
  #    exclude:
  #      - org.springframework.ai.model.google.genai.autoconfigure.chat.GoogleGenAiChatAutoConfiguration
  ai:
    ollama:
      base-url: ${OLLAMA_AI_URL}
      chat:
        options:
          model: ${OLLAMA_AI_MODEL}
          temperature: 0.2
          top-p: 0.85
          num-predict: 2048