spring:
#  autoconfigure:
#    exclude:
#      - org.springframework.ai.model.google.genai.autoconfigure.chat.GoogleGenAiChatAutoConfiguration
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          #model: qwen3.5:2b
          #model: llama3.2:3b
          #model: qwen3.5:latest
          model: minimax-m3:cloud